default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: track_my_spending_development
  username: nitrous

test:
  <<: *default
  database: track_my_spending_test
  username: nitrous

production:
  <<: *default
  database: db/production.sqlite3
